version: 2
project_name: docker-metrics

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: docker-metrics-linux
    env:
      - CGO_ENABLED=1
      - CC_linux_amd64=gcc
      - CXX_linux_amd64=g++
      - CC_linux_arm64=aarch64-linux-gnu-gcc
      - CXX_linux_arm64=aarch64-linux-gnu-g++
      - 'CC={{ index .Env (print "CC_" .Os "_" .Arch) }}'
      - 'CXX={{ index .Env (print "CXX_" .Os "_" .Arch) }}'
    main: ./cmd/docker-metrics
    binary: docker-metrics
    goos: [linux]
    goarch: [amd64, arm64]
  - id: docker-metrics-darwin
    env:
      - CGO_ENABLED=1
    main: ./cmd/docker-metrics
    binary: docker-metrics
    goos: [darwin]
    goarch: [amd64, arm64]

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

homebrew_casks:
  - name: docker-metrics
    binaries: [XXX]
    description: "XXX is a tool"
    homepage: "https://github.com/go-go-golems/docker-metrics"
    repository:
      owner: go-go-golems
      name: homebrew-go-go-go
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    url:
      verified: github.com/go-go-golems/docker-metrics/

nfpms:
  - id: packages
    vendor: GO GO GOLEMS
    homepage: https://github.com/go-go-golems/docker-metrics
    maintainer: Manuel Odendahl <wesen@ruinwesen.com>
    description: XXX is a tool
    license: MIT
    formats: [deb, rpm]
    release: 1
    section: default
    priority: extra
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

publishers:
  - name: fury.io
    ids: [packages]
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/go-go-golems/

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
