package httpapi

import (
	"embed"
	"io/fs"
	"net/http"
	"os"
	"path"
	"strings"
)

// The built frontend is embedded so the binary is self-contained. It is
// generated by `make build-web` (pnpm build in web/, copied to dist/).
//
//go:embed all:dist
var embeddedDist embed.FS

func embeddedStaticFS() fs.FS {
	sub, err := fs.Sub(embeddedDist, "dist")
	if err != nil {
		return embeddedDist
	}
	return sub
}

// handleStatic serves the SPA from the on-disk StaticDir when present, otherwise
// from the embedded build. Unknown paths fall back to index.html so client-side
// routes like /ide work.
func (s *Server) handleStatic(w http.ResponseWriter, r *http.Request) {
	if dir := s.cfg.StaticDir; dir != "" {
		if info, err := os.Stat(dir); err == nil && info.IsDir() {
			s.serveFS(w, r, os.DirFS(dir))
			return
		}
	}
	s.serveFS(w, r, embeddedStaticFS())
}

func (s *Server) serveFS(w http.ResponseWriter, r *http.Request, filesystem fs.FS) {
	name := strings.TrimPrefix(path.Clean("/"+r.URL.Path), "/")
	if name == "" {
		name = "index.html"
	}
	if f, err := filesystem.Open(name); err == nil {
		info, statErr := f.Stat()
		f.Close()
		if statErr == nil && !info.IsDir() {
			http.FileServer(http.FS(filesystem)).ServeHTTP(w, r)
			return
		}
	}
	// SPA fallback: serve index.html for client-side routes.
	index, err := fs.ReadFile(filesystem, "index.html")
	if err != nil {
		s.serveFallback(w, r)
		return
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	_, _ = w.Write(index)
}
