- type: local
  path: /Users/manuel.odendahl/Downloads/dockermetrics-ide.html
  lastFetched: 2026-10-06T14:53:18.530337-04:00
- type: local
  path: /Users/manuel.odendahl/Downloads/dockermetrics-ide (2).html
  lastFetched: 2026-10-06T15:26:39.449521-04:00
